fun linear_arr_search(arr, arr_val) {
	let i = 0;
	let index = -1;
	while (i < len(arr)) {
		if (arr[i] == arr_val) {
			index = i;
			i = len(arr);
		}
		i = i + 1;
	}
	return index;
}

fun binary_arr_search(arr, arr_val) {
	let low = 0;
	let high = len(arr) - 1;
	let res = -1;
	while (low <= high) {
		let mid = low + (high - low) / 2;
		if (arr[mid] == arr_val) {
			res = mid;
			low = high + 1;
		} else if (arr[mid] < arr_val) {
			low = mid + 1;
		} else {
			high = mid - 1;
		}
	}
	return res;
}

fun eval_tests(arr_f, arr_c) {
	if (len(arr_f) != len(arr_c)) {
		print("input mismatch");
	}
	let length = len(arr_f);
	let i = 0;
	while (i < length) {
		if (arr_f[i] == arr_c[i]) {
			print("test passed");
		} else {
			print("test failed");
		}
		i = i + 1;
	}
}

fun lin_tests() {
	let arr = [5, 4, 3, 2, 1];
	let arr_f = [0, 0, 0, 0];
	let arr_c = [2, -1, 4, 0];

	arr_f[0] = linear_arr_search(arr, 3);
	arr_f[1] = linear_arr_search(arr, 0);
	arr_f[2] = linear_arr_search(arr, 1);
	arr_f[3] = linear_arr_search(arr, 5);
	
	eval_tests(arr_f, arr_c);
}

fun bin_tests() {
	let arr = [1, 2, 3, 4, 5];
	let arr_f = [0, 0, 0, 0];
	let arr_c = [2, -1, 0, 4];

	arr_f[0] = binary_arr_search(arr, 3);
	arr_f[1] = binary_arr_search(arr, 0);
	arr_f[2] = binary_arr_search(arr, 1);
	arr_f[3] = binary_arr_search(arr, 5);

	eval_tests(arr_f, arr_c);
}

fun main() {
	print("linear search tests:");
	lin_tests();
	print("binary search tests:");
	bin_tests();
}

main();
